# The bearer-token secret. One token per caller in var.callers is generated by
# random_password so no human ever authors a token and none is ever committed
# (R19). The secret's value is the flat JSON object the identity layer parses:
#
#   { "<token>": { "caller": "<name>", "team": "<team>" }, ... }
#
# verified against gate/identity.py (_validate_tokens): each key is the raw
# token string, each value an object with string "caller" and "team".
#
# R19 nuance, acknowledged explicitly: a generated token necessarily lives in
# local Terraform state, which is gitignored (R40). What R19 forbids is a token
# in the repo, in the image, or as a plaintext INPUT to Terraform. Generating it
# here means it is an OUTPUT that exists only in state and in Secrets Manager --
# never authored, never committed, never an input. It is also kept out of plain
# Terraform outputs (see outputs.tf): the operator fetches it with the emitted
# get-secret-value command instead.

# random_password over random_string because random_password marks its result
# sensitive, so it never prints in a plan diff. length >= 40 for entropy;
# special = false so every token is header-safe (an Authorization: Bearer value
# with no characters that need escaping).
resource "random_password" "token" {
  for_each = var.callers

  length  = 48
  special = false
}

# Precondition: every team named in var.callers must be defined in policy.yaml,
# or the gate would refuse to boot on a token mapped to an unknown team. Catch
# it at plan time here rather than as a task crash-loop after apply. policy.yaml
# is read from the repo root (two levels up from this stack). teams is a map, so
# its keys are the defined team names.
locals {
  policy_teams           = keys(yamldecode(file("${path.module}/../../policy.yaml")).teams)
  configured_teams       = distinct(values(var.callers))
  undefined_caller_teams = setsubtract(toset(local.configured_teams), toset(local.policy_teams))

  # The token map written into the secret. Built from the generated passwords so
  # the plaintext appears only in state, never in configuration.
  token_map = {
    for caller, team in var.callers :
    random_password.token[caller].result => {
      caller = caller
      team   = team
    }
  }
}

resource "aws_secretsmanager_secret" "tokens" {
  name        = "${var.project_name}-tokens"
  description = "Bearer token -> caller/team map for the mcp-bouncer gate. Generated; never authored."

  # recovery_window_in_days = 0 so a destroy immediately deletes the secret
  # instead of scheduling it for recovery. Without this, the name lingers in a
  # "scheduled for deletion" state and a re-apply of this disposable stack
  # collides on the name (R41: destroy leaves nothing, and re-apply just works).
  recovery_window_in_days = 0

  # No kms_key_id: the AWS-managed key (aws/secretsmanager) encrypts the secret,
  # so the task role needs no kms:Decrypt grant (NOTES: kms:Decrypt only for a
  # customer-managed key). Keeps the IAM surface minimal.

  lifecycle {
    precondition {
      condition     = length(local.undefined_caller_teams) == 0
      error_message = "callers reference team(s) not defined in policy.yaml: ${join(", ", local.undefined_caller_teams)}. Add the team block to policy.yaml or fix the caller's team."
    }
  }

  tags = { Name = "${var.project_name}-tokens" }
}

resource "aws_secretsmanager_secret_version" "tokens" {
  secret_id     = aws_secretsmanager_secret.tokens.id
  secret_string = jsonencode(local.token_map)
}

# --- LiteLLM master key (R55, D6.10) ---------------------------------------
#
# LiteLLM's master key -- and, without a database, its ONLY key and its ADMIN key
# (R55, D6.6). Generated here so no human authors it and it never appears in
# configuration, the image, or the repository; it lives only in local state
# (gitignored, R40) and in Secrets Manager, and is injected into the container
# via the `secrets` block as LITELLM_MASTER_KEY.
#
# length 48 (>= 40 for entropy) and special = false so the value is header-safe.
# It is given an `sk-` prefix: LiteLLM matches the master key with an exact
# secrets.compare_digest (verified: proxy/auth/user_api_key_auth.py:2036), so a
# non-`sk-` value would still authenticate, but several virtual-key code paths
# branch on token.startswith("sk-") (e.g. proxy/proxy_server.py:3584), so the
# `sk-` convention is the safe choice.
resource "random_password" "litellm_master_key" {
  length  = 48
  special = false
}

resource "aws_secretsmanager_secret" "litellm_master_key" {
  name        = "${var.project_name}-litellm-master-key"
  description = "LiteLLM master/admin key for the mcp-bouncer gateway. Generated; never authored."

  # Same disposable-stack reasoning as the token secret: immediate delete on
  # destroy so a re-apply does not collide on the name (R41).
  recovery_window_in_days = 0

  # No kms_key_id: the AWS-managed key encrypts it, so the execution role needs
  # no kms:Decrypt grant.

  tags = { Name = "${var.project_name}-litellm-master-key" }
}

# A PLAIN STRING, not JSON: the container reads LITELLM_MASTER_KEY as the literal
# key value, and the ECS `secrets` block injects the whole SecretString as the
# env var. The `sk-` prefix is prepended here.
resource "aws_secretsmanager_secret_version" "litellm_master_key" {
  secret_id     = aws_secretsmanager_secret.litellm_master_key.id
  secret_string = "sk-${random_password.litellm_master_key.result}"
}
