# The bearer-token secret. One token per caller in var.callers is generated by
# random_password so no human authors a token and none is committed; it lives
# only in state (gitignored) and in Secrets Manager, never in the repo or image.

# random_password marks its result sensitive, so it never prints in a plan diff.
# length >= 40 for entropy; special = false so every token is header-safe for an
# Authorization: Bearer value with no characters that need escaping.
resource "random_password" "token" {
  for_each = var.callers

  length  = 48
  special = false
}

# Every team named in var.callers must be defined in policy.yaml, or the gate
# refuses to boot on a token mapped to an unknown team. Caught at plan time here
# rather than as a task crash-loop; policy.yaml is read from the repo root.
locals {
  policy_teams           = keys(yamldecode(file("${path.module}/../../policy.yaml")).teams)
  configured_teams       = distinct(values(var.callers))
  undefined_caller_teams = setsubtract(toset(local.configured_teams), toset(local.policy_teams))

  # The token map written into the secret. Built from the generated passwords so
  # the plaintext appears only in state, never in configuration.
  token_map = {
    for caller, team in var.callers :
    random_password.token[caller].result => {
      caller = caller
      team   = team
    }
  }
}

resource "aws_secretsmanager_secret" "tokens" {
  name        = "${var.project_name}-tokens"
  description = "Bearer token -> caller/team map for the mcp-bouncer gate. Generated; never authored."

  # recovery_window_in_days = 0 so a destroy immediately deletes the secret
  # instead of scheduling it. Otherwise the name lingers in "scheduled for
  # deletion" state and a re-apply of this disposable stack collides on it.
  recovery_window_in_days = 0

  # No kms_key_id: the AWS-managed key (aws/secretsmanager) encrypts the secret,
  # so the task role needs no kms:Decrypt grant, which keeps the IAM surface
  # minimal.

  lifecycle {
    precondition {
      condition     = length(local.undefined_caller_teams) == 0
      error_message = "callers reference team(s) not defined in policy.yaml: ${join(", ", local.undefined_caller_teams)}. Add the team block to policy.yaml or fix the caller's team."
    }
  }

  tags = { Name = "${var.project_name}-tokens" }
}

resource "aws_secretsmanager_secret_version" "tokens" {
  secret_id     = aws_secretsmanager_secret.tokens.id
  secret_string = jsonencode(local.token_map)
}

# --- LiteLLM master key ----------------------------------------------------

# LiteLLM's master key, and without a database its only key and its admin key.
# Generated so no human authors it; it lives only in state (gitignored) and in
# Secrets Manager. special = false keeps it header-safe; the `sk-` prefix is set.
resource "random_password" "litellm_master_key" {
  length  = 48
  special = false
}

resource "aws_secretsmanager_secret" "litellm_master_key" {
  name        = "${var.project_name}-litellm-master-key"
  description = "LiteLLM master/admin key for the mcp-bouncer gateway. Generated; never authored."

  # Same disposable-stack reasoning as the token secret: immediate delete on
  # destroy so a re-apply does not collide on the name.
  recovery_window_in_days = 0

  # No kms_key_id: the AWS-managed key encrypts it, so the execution role needs
  # no kms:Decrypt grant.

  tags = { Name = "${var.project_name}-litellm-master-key" }
}

# A plain string, not JSON: the container reads LITELLM_MASTER_KEY as the literal
# key value, and the ECS `secrets` block injects the whole SecretString as the
# env var. The `sk-` prefix is prepended here.
resource "aws_secretsmanager_secret_version" "litellm_master_key" {
  secret_id     = aws_secretsmanager_secret.litellm_master_key.id
  secret_string = "sk-${random_password.litellm_master_key.result}"
}
